# Meta
title: Jon Rohan's Styleguide
baseurl: /styleguide
google_analyics_id: UA-543420-18

# Setup
permalink: none
exclude:
  - CONTRIBUTING.md
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock

# Dependencies
kramdown:
  input: GFM
markdown: kramdown

gems:
  - jemoji

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
