# Meta
title: Jon Rohan's Styleguide
baseurl: /styleguide
url: http://jonrohan.codes
google_analyics_id: UA-543420-18

# Setup
permalink: /:categories-:title.html
show_drafts: true
unpublished: true
exclude:
  - CONTRIBUTING.md
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - "**/readme.md"

include:
  - .editorconfig
  - .scss-lint.yml

markdown: redcarpet

gems:
  - jemoji

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      published: true
      date: 2015-01-01 00:00:00

sass:
  sass_dir: ""
  style: compressed
